development:
  adapter: postgresql
  encoding: unicode
  database: fplmoneyball_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: fplmoneyball_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: fplmoneyball_production
  pool: 5
  username: 
  password: